GetDroppedFiles implementation
IBM/aspera-connect-sdk-js pull request #67
Opened 2024-06-05 13:55 UTC by JAHMCR

### Requirement
Closes [#2177](https://github.ibm.com/Aspera/connect-app/issues/2177)

Add a `getDroppedFiles` method to the public interface that could be used by clients to get dropped files manually. Could be useful for cases like this where `setDragDropTargets` isn't used.

### Implementation

Added a new `getDroppedFiles` function to the public interface.

2024-06-18 22:55 UTC, dwosk requested changes
Can you see if there's an easy way for downstream apps to get errors via the callback? I see that was supported in the original function we used to expose, so having something similar would be nice. See `types.Callbacks`.

2024-06-19 03:19 UTC, dwosk approved these changes
Actually thanks I think it already has support for the error callback, I just went based off what is in setDragDropTargets.

Thanks @JAHMCR!

2024-06-19 03:22 UTC, merged

2024-07-09 20:34 UTC, dwosk commented
Hi @mattastarita sorry for the delay. Let me look into releasing a new version ASAP and get back to you.

2024-07-10 15:06 UTC, mattastarita commented
Thank you

2024-07-11 20:06 UTC, dwosk commented
@mattastarita there were some changes made to the IBM organization in GitHub and we're waiting on the responsible team to whitelist some of the GitHub Actions we use for deployment. Sorry, I will ping them again today to try and speed it along.

2024-07-19 08:29 UTC, mattastarita commented
Hi a @dwosk, hope you are well. Any news on your side?
Thanks

2024-07-19 10:40 UTC, dwosk commented
Hi, yes we are in the process of updating our deployment workflows as the IBM policy has changed and we can no longer use some of the actions from the marketplace.

The PR is currently being reviewed here: #71

2024-07-24 14:41 UTC, mattastarita commented
Ok thanks, looking forward to it

2024-07-30 01:20 UTC, gegles commented
@mattastarita, v5.0.1, with the fix you requested has finally been [released](https://github.com/IBM/aspera-connect-sdk-js/releases/tag/v5.0.1)... Let us know. Thx!